services:
  # Backend API Service
  - type: web
    name: portfolio-backend
    runtime: python
    buildCommand: "cd backend && pip install -r requirements_simple.txt"
    startCommand: "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"
    plan: starter
    rootDir: .
    region: oregon
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: "0.0.0.0"
      - key: CORS_ORIGINS
        value: "https://portfolio-frontend-xxxx.onrender.com,http://localhost:3000"

# Note: Frontend will be deployed separately as a static site
# Create this as a separate static site service in Render dashboard